# This file is generated by https://github.com:pylover/python-makelib
import os.path
import re

from setuptools import setup, find_packages


# reading package's version (same way sqlalchemy does)
with open(
    os.path.join(os.path.dirname(__file__), 'pytest_fixkit', '__init__.py')
) as v_file:
    package_version = \
        re.compile('.*__version__ = \'(.*?)\'', re.S) \
        .match(v_file.read()) \
        .group(1)


dependencies = [
    'pytest',
    'redis',
]


setup(
    name='pytest-fixkit',
    version=package_version,
    author='Vahid Mardani',
    author_email='vahid.mardani@gmail.com',
    url='http://github.com/pylover/pytest-fixkit',
    description='A very micro http framework.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',  # This is important!
    install_requires=dependencies,
    license='MIT',
    packages=find_packages(
        where='.',
        include=['pytest_fixkit'],
        exclude=['tests']
    ),
    # entry_points={
    #     'pytest11': [
    #         'fixkit = pytest_fixkit'
    #     ]
    # },
    classifiers=[
        'Framework :: Pytest',
        'Development Status :: 5 - Production/Stable',
        'Natural Language :: English',
        'Intended Audience :: Developers',
        'Topic :: Software Development',
        'Topic :: Software Development :: Libraries',
        'Topic :: Software Development :: Testing',
        'Topic :: Software Development :: Quality Assurance',
        'Topic :: System :: Filesystems',
        'Topic :: System :: Networking',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Database',
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ]
)
